# Generated by Django 4.1.5 on 2023-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_countinstock_product_qty_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
